# Generated by Django 2.2.6 on 2019-11-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='place_type',
            field=models.CharField(choices=[('ОБЩ', 'Общий'), ('ПЛЦ', 'Плацкартный'), ('КУП', 'Купейный')], default='', max_length=3),
        ),
    ]
