# Generated by Django 2.2.6 on 2019-11-07 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20191104_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(choices=[('ОБЩ', 'Общий'), ('ПЛЦ', 'Плацкартный'), ('КУП', 'Купейный')], default='', max_length=3)),
                ('arr_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arr_st', to='reservation.Train')),
                ('dep_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_st', to='reservation.Train')),
            ],
            options={
                'verbose_name_plural': 'reservations',
                'ordering': ['pk'],
            },
        ),
    ]
