# Generated by Django 2.2.6 on 2019-11-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comfort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(choices=[('ОБЩ', 'Общий'), ('ПЛЦ', 'Плацкартный'), ('КУП', 'Купейный')], default='', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'place_types',
            },
        ),
        migrations.AlterField(
            model_name='train',
            name='num',
            field=models.CharField(default='', max_length=3, unique=True),
        ),
        migrations.DeleteModel(
            name='Reservate',
        ),
    ]
