# Generated by Django 2.2.6 on 2019-11-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20191111_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comfort',
            options={'ordering': ['pk'], 'verbose_name_plural': 'place_types'},
        ),
    ]
