# Generated by Django 2.2.6 on 2019-11-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='reservation.Passenger')),
                ('train_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='reservation.Train')),
            ],
            options={
                'verbose_name_plural': 'tickets',
                'ordering': ['pk'],
            },
        ),
    ]
