# Generated by Django 2.2.6 on 2019-10-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20191021_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(unique=True)),
                ('dep_station', models.TextField(unique=True)),
                ('arr_station', models.TextField(unique=True)),
                ('dep_time', models.TimeField()),
                ('arr_time', models.TimeField()),
                ('carriage_type', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'trains',
                'ordering': ['num'],
            },
        ),
    ]
