# Generated by Django 2.2.6 on 2019-10-26 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_train'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['dep_station'], 'verbose_name_plural': 'trains'},
        ),
        migrations.AlterField(
            model_name='train',
            name='arr_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='reservation.City'),
        ),
        migrations.AlterField(
            model_name='train',
            name='dep_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='reservation.City'),
        ),
    ]
