# Generated by Django 2.2.6 on 2019-10-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField()),
                ('name', models.TextField()),
                ('patronymic', models.TextField()),
                ('phone', models.PositiveIntegerField(unique=True)),
                ('passport_series', models.CharField(max_length=2)),
                ('passport_number', models.PositiveIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'passengers',
                'ordering': ['surname'],
            },
        ),
    ]
