# Generated by Django 2.2.6 on 2019-10-27 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(unique=True)),
                ('amount_place', models.PositiveSmallIntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'carriages',
                'ordering': ['type'],
            },
        ),
        migrations.AlterField(
            model_name='train',
            name='carriage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_carriage', to='reservation.Carriage'),
        ),
    ]
