# Generated by Django 2.2.6 on 2019-10-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20191027_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='carriage_type',
        ),
        migrations.AddField(
            model_name='train',
            name='place_type',
            field=models.CharField(
                choices=[('ОБЩ', 'Общий'), ('ПЛЦ', 'Плацкартный'), ('КУП', 'Купейный'), (None, '---')],
                default='', max_length=3
            ),
        ),
        migrations.DeleteModel(
            name='Carriage',
        ),
    ]
