# Generated by Django 2.2.6 on 2019-10-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20191029_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
